name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # изменено с main на master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Copy CNAME if exists
        run: if [ -f CNAME ]; then cp CNAME dist/; fi
        
      - name: Copy 404.html
        run: cp dist/index.html dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # папка с собранным проектом
          branch: gh-pages # ветка, в которую будет деплоиться сайт
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }} 